// flow-typed signature: b0a2903675507d2432ca1af1410c055f
// flow-typed version: <<STUB>>/@types/autoprefixer_v^9.1.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/autoprefixer' {
  declare module.exports: any;
}
