// flow-typed signature: 65e5e835a5465b89f3a043bd0b1fe401
// flow-typed version: <<STUB>>/@types/autoprefixer_v^9.1.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/autoprefixer' {
  declare module.exports: any;
}
