// flow-typed signature: 80a539b94ef1b4068860ff158b6dcd05
// flow-typed version: <<STUB>>/@types/express_v^4.16.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
