// flow-typed signature: f10f8fb1530b62e31cc86ec6362306d9
// flow-typed version: <<STUB>>/@types/fs-extra_v^5.0.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/fs-extra' {
  declare module.exports: any;
}
