// flow-typed signature: 5b531cc3c13c9b0eefc21a3c4080a365
// flow-typed version: <<STUB>>/@types/fs-extra_v^5.0.4/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/fs-extra' {
  declare module.exports: any;
}
