// flow-typed signature: 9c33a534cd7b2564521e66e6ed95d81c
// flow-typed version: <<STUB>>/@types/html-webpack-plugin_v^3.2.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/html-webpack-plugin' {
  declare module.exports: any;
}
