// flow-typed signature: 155c87850e4f221cee3e1792e6a394d8
// flow-typed version: <<STUB>>/@types/http-proxy-middleware_v^0.19.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/http-proxy-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/http-proxy-middleware' {
  declare module.exports: any;
}
