// flow-typed signature: 3bd070228f7cd68afb758b40990d28ea
// flow-typed version: <<STUB>>/@types/http-proxy-middleware_v^0.19.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/http-proxy-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/http-proxy-middleware' {
  declare module.exports: any;
}
