// flow-typed signature: 93e9da7d1c049fe45ea35cf19d67c7de
// flow-typed version: <<STUB>>/@types/jest_v^23.3.12/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
