// flow-typed signature: 8149c8eb6a3c1f37bd363c711b67c20e
// flow-typed version: <<STUB>>/@types/jest_v^23.3.10/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
