// flow-typed signature: 3edf15646272008579fe8c9d6ce6feca
// flow-typed version: <<STUB>>/@types/js-md5_v^0.4.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/js-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/js-md5' {
  declare module.exports: any;
}
