// flow-typed signature: 67c8f81b1057c51d47d8a5079340cc8f
// flow-typed version: <<STUB>>/@types/js-md5_v^0.4.2/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/js-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/js-md5' {
  declare module.exports: any;
}
