// flow-typed signature: 4fe9a35bbf0b63edad065acc22f4c081
// flow-typed version: <<STUB>>/@types/mini-css-extract-plugin_v^0.2.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mini-css-extract-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mini-css-extract-plugin' {
  declare module.exports: any;
}
