// flow-typed signature: 7bb7ce4504f5e0037a30f68cfebf61b1
// flow-typed version: <<STUB>>/@types/node_v^10.12.10/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
