// flow-typed signature: 410787082a76afac46096a15666b076f
// flow-typed version: <<STUB>>/@types/node_v^10.12.18/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
