// flow-typed signature: 2386dd13bf3992fcb742ea9389fa3818
// flow-typed version: <<STUB>>/@types/optimize-css-assets-webpack-plugin_v^1.3.3/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/optimize-css-assets-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/optimize-css-assets-webpack-plugin' {
  declare module.exports: any;
}
