// flow-typed signature: 10f9a97ee2f0c0b28f47c34cd74474e5
// flow-typed version: <<STUB>>/@types/qs_v^6.5.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/qs' {
  declare module.exports: any;
}
