// flow-typed signature: e27596fc057e76c36d492e79a8624690
// flow-typed version: <<STUB>>/@types/qs_v^6.5.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/qs' {
  declare module.exports: any;
}
