// flow-typed signature: 77fcec29482367c8989e1bb7c781d206
// flow-typed version: <<STUB>>/@types/react_v^16.7.9/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
