// flow-typed signature: f64945c9cbdef424ec1e12ed206855c0
// flow-typed version: <<STUB>>/@types/react_v^16.7.17/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
