// flow-typed signature: 6e7e933b2fdde68c1d86826a4a64d5c4
// flow-typed version: <<STUB>>/@types/react-loadable_v^5.4.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-loadable' {
  declare module.exports: any;
}
