// flow-typed signature: 04c981ac639779df5654d368a8230cfa
// flow-typed version: <<STUB>>/@types/react-loadable_v^5.4.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-loadable' {
  declare module.exports: any;
}
