// flow-typed signature: 1a1de23d195748cb5c4a12e02d93be6f
// flow-typed version: <<STUB>>/@types/react-dom_v^16.0.10/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
