// flow-typed signature: 1454f1fe60472241e19e1c2f8dff3727
// flow-typed version: <<STUB>>/@types/react_v^16.7.7/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
