// flow-typed signature: c1ccc5044f37f2fb6c7dd0710074b3d4
// flow-typed version: <<STUB>>/@types/webpack_v^4.4.21/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
