// flow-typed signature: c84cb9e9f69358d76bc5cbc4d177f202
// flow-typed version: <<STUB>>/@types/webpack-dev-server_v^3.1.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack-dev-server' {
  declare module.exports: any;
}
