// flow-typed signature: 50f0640215f245453d109cc33752574c
// flow-typed version: <<STUB>>/@types/webpack-merge_v^4.1.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack-merge' {
  declare module.exports: any;
}
