// flow-typed signature: 059a29101b9b4afb55084b9edc7323a1
// flow-typed version: <<STUB>>/@types/webpack_v^4.4.20/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
