// flow-typed signature: 222519f21642d69c0625661a08440aed
// flow-typed version: <<STUB>>/babel-register-ts_v^7.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-register-ts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-register-ts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-register-ts/index' {
  declare module.exports: $Exports<'babel-register-ts'>;
}
declare module 'babel-register-ts/index.js' {
  declare module.exports: $Exports<'babel-register-ts'>;
}
