// flow-typed signature: 640eccf1a8b08f54d3c25d0389b12cba
// flow-typed version: <<STUB>>/connect-timeout_v^1.9.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-timeout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-timeout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect-timeout/index' {
  declare module.exports: $Exports<'connect-timeout'>;
}
declare module 'connect-timeout/index.js' {
  declare module.exports: $Exports<'connect-timeout'>;
}
