// flow-typed signature: 6bddd9dde978671e12d02a16267b764b
// flow-typed version: <<STUB>>/fork-ts-checker-webpack-plugin_v0.5.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fork-ts-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fork-ts-checker-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fork-ts-checker-webpack-plugin/lib/CancellationToken' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/cluster' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/FilesRegister' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/FilesWatcher' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/codeframeFormatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/formatter/defaultFormatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/IncrementalChecker' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/Message' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/NormalizedMessage' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/service' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/VueProgram' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/WorkResult' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin/lib/WorkSet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fork-ts-checker-webpack-plugin/lib/CancellationToken.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/CancellationToken'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/cluster.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/cluster'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/FilesRegister.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/FilesRegister'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/FilesWatcher.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/FilesWatcher'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/codeframeFormatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/codeframeFormatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/formatter/defaultFormatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/formatter/defaultFormatter'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/IncrementalChecker.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/IncrementalChecker'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/index'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/Message.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/Message'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/NormalizedMessage.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/NormalizedMessage'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/service.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/service'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/VueProgram.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/VueProgram'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/WorkResult.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/WorkResult'>;
}
declare module 'fork-ts-checker-webpack-plugin/lib/WorkSet.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin/lib/WorkSet'>;
}
