// flow-typed signature: fad2804dbb800f6f6ce5387e9c81d426
// flow-typed version: <<STUB>>/fork-ts-checker-notifier-webpack-plugin_v0.7.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fork-ts-checker-notifier-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fork-ts-checker-notifier-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fork-ts-checker-notifier-webpack-plugin/index' {
  declare module.exports: $Exports<'fork-ts-checker-notifier-webpack-plugin'>;
}
declare module 'fork-ts-checker-notifier-webpack-plugin/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-notifier-webpack-plugin'>;
}
