// flow-typed signature: 06ce6a17caa2654a18e9c3931c032d9b
// flow-typed version: <<STUB>>/react-keeper_v^2.1.9/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-keeper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-keeper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-keeper/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-keeper/CacheLink' {
  declare module.exports: any;
}

declare module 'react-keeper/HashRouter' {
  declare module.exports: any;
}

declare module 'react-keeper/HistoryControl' {
  declare module.exports: any;
}

declare module 'react-keeper/InnerRouter' {
  declare module.exports: any;
}

declare module 'react-keeper/Link' {
  declare module.exports: any;
}

declare module 'react-keeper/match/compilePattern' {
  declare module.exports: any;
}

declare module 'react-keeper/match/matchPath' {
  declare module.exports: any;
}

declare module 'react-keeper/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-keeper/middleware/RouteCache' {
  declare module.exports: any;
}

declare module 'react-keeper/middleware/RouteFilter' {
  declare module.exports: any;
}

declare module 'react-keeper/middleware/RouteIndex' {
  declare module.exports: any;
}

declare module 'react-keeper/middleware/RouteMiss' {
  declare module.exports: any;
}

declare module 'react-keeper/middleware/RouteRedirect' {
  declare module.exports: any;
}

declare module 'react-keeper/Route' {
  declare module.exports: any;
}

declare module 'react-keeper/RouteBase' {
  declare module.exports: any;
}

declare module 'react-keeper/Router' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/CacheOfLinkControl' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/CacheOfTagControl' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/functional' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/Logger' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/RouteControl' {
  declare module.exports: any;
}

declare module 'react-keeper/utils/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-keeper/BrowserRouter.js' {
  declare module.exports: $Exports<'react-keeper/BrowserRouter'>;
}
declare module 'react-keeper/CacheLink.js' {
  declare module.exports: $Exports<'react-keeper/CacheLink'>;
}
declare module 'react-keeper/HashRouter.js' {
  declare module.exports: $Exports<'react-keeper/HashRouter'>;
}
declare module 'react-keeper/HistoryControl.js' {
  declare module.exports: $Exports<'react-keeper/HistoryControl'>;
}
declare module 'react-keeper/index' {
  declare module.exports: $Exports<'react-keeper'>;
}
declare module 'react-keeper/index.js' {
  declare module.exports: $Exports<'react-keeper'>;
}
declare module 'react-keeper/InnerRouter.js' {
  declare module.exports: $Exports<'react-keeper/InnerRouter'>;
}
declare module 'react-keeper/Link.js' {
  declare module.exports: $Exports<'react-keeper/Link'>;
}
declare module 'react-keeper/match/compilePattern.js' {
  declare module.exports: $Exports<'react-keeper/match/compilePattern'>;
}
declare module 'react-keeper/match/matchPath.js' {
  declare module.exports: $Exports<'react-keeper/match/matchPath'>;
}
declare module 'react-keeper/MemoryRouter.js' {
  declare module.exports: $Exports<'react-keeper/MemoryRouter'>;
}
declare module 'react-keeper/middleware/RouteCache.js' {
  declare module.exports: $Exports<'react-keeper/middleware/RouteCache'>;
}
declare module 'react-keeper/middleware/RouteFilter.js' {
  declare module.exports: $Exports<'react-keeper/middleware/RouteFilter'>;
}
declare module 'react-keeper/middleware/RouteIndex.js' {
  declare module.exports: $Exports<'react-keeper/middleware/RouteIndex'>;
}
declare module 'react-keeper/middleware/RouteMiss.js' {
  declare module.exports: $Exports<'react-keeper/middleware/RouteMiss'>;
}
declare module 'react-keeper/middleware/RouteRedirect.js' {
  declare module.exports: $Exports<'react-keeper/middleware/RouteRedirect'>;
}
declare module 'react-keeper/Route.js' {
  declare module.exports: $Exports<'react-keeper/Route'>;
}
declare module 'react-keeper/RouteBase.js' {
  declare module.exports: $Exports<'react-keeper/RouteBase'>;
}
declare module 'react-keeper/Router.js' {
  declare module.exports: $Exports<'react-keeper/Router'>;
}
declare module 'react-keeper/utils/CacheOfLinkControl.js' {
  declare module.exports: $Exports<'react-keeper/utils/CacheOfLinkControl'>;
}
declare module 'react-keeper/utils/CacheOfTagControl.js' {
  declare module.exports: $Exports<'react-keeper/utils/CacheOfTagControl'>;
}
declare module 'react-keeper/utils/functional.js' {
  declare module.exports: $Exports<'react-keeper/utils/functional'>;
}
declare module 'react-keeper/utils/Logger.js' {
  declare module.exports: $Exports<'react-keeper/utils/Logger'>;
}
declare module 'react-keeper/utils/RouteControl.js' {
  declare module.exports: $Exports<'react-keeper/utils/RouteControl'>;
}
declare module 'react-keeper/utils/Util.js' {
  declare module.exports: $Exports<'react-keeper/utils/Util'>;
}
