// flow-typed signature: 437c10c25415cbc212ea424a934a30d2
// flow-typed version: <<STUB>>/rxjs-hooks_v^0.2.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rxjs-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rxjs-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rxjs-hooks/esm/__test__/find' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/__test__/use-event-callback.spec' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/__test__/use-observable.spec' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/index' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/type' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/use-event-callback' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/esm/use-observable' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/jest.config' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/tools/test-setup' {
  declare module.exports: any;
}

declare module 'rxjs-hooks/tools/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rxjs-hooks/esm/__test__/find.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/__test__/find'>;
}
declare module 'rxjs-hooks/esm/__test__/use-event-callback.spec.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/__test__/use-event-callback.spec'>;
}
declare module 'rxjs-hooks/esm/__test__/use-observable.spec.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/__test__/use-observable.spec'>;
}
declare module 'rxjs-hooks/esm/index.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/index'>;
}
declare module 'rxjs-hooks/esm/type.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/type'>;
}
declare module 'rxjs-hooks/esm/use-event-callback.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/use-event-callback'>;
}
declare module 'rxjs-hooks/esm/use-observable.js' {
  declare module.exports: $Exports<'rxjs-hooks/esm/use-observable'>;
}
declare module 'rxjs-hooks/jest.config.js' {
  declare module.exports: $Exports<'rxjs-hooks/jest.config'>;
}
declare module 'rxjs-hooks/tools/test-setup.js' {
  declare module.exports: $Exports<'rxjs-hooks/tools/test-setup'>;
}
declare module 'rxjs-hooks/tools/webpack.config.js' {
  declare module.exports: $Exports<'rxjs-hooks/tools/webpack.config'>;
}
