// flow-typed signature: 37aa3abffe70a0f39fb6ecd8a8bb089e
// flow-typed version: <<STUB>>/tsconfig-paths-webpack-plugin_v^3.2.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tsconfig-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tsconfig-paths-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tsconfig-paths-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'tsconfig-paths-webpack-plugin/lib/logger' {
  declare module.exports: any;
}

declare module 'tsconfig-paths-webpack-plugin/lib/options' {
  declare module.exports: any;
}

declare module 'tsconfig-paths-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tsconfig-paths-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'tsconfig-paths-webpack-plugin/lib/index'>;
}
declare module 'tsconfig-paths-webpack-plugin/lib/logger.js' {
  declare module.exports: $Exports<'tsconfig-paths-webpack-plugin/lib/logger'>;
}
declare module 'tsconfig-paths-webpack-plugin/lib/options.js' {
  declare module.exports: $Exports<'tsconfig-paths-webpack-plugin/lib/options'>;
}
declare module 'tsconfig-paths-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'tsconfig-paths-webpack-plugin/lib/plugin'>;
}
