// flow-typed signature: 0ac0c6376f4140ade2849f6453ff6560
// flow-typed version: <<STUB>>/typings-for-css-modules-loader_v^1.7.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typings-for-css-modules-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typings-for-css-modules-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typings-for-css-modules-loader/lib/cssModuleHelper' {
  declare module.exports: any;
}

declare module 'typings-for-css-modules-loader/lib/cssModuleToInterface' {
  declare module.exports: any;
}

declare module 'typings-for-css-modules-loader/lib/index' {
  declare module.exports: any;
}

declare module 'typings-for-css-modules-loader/lib/logger' {
  declare module.exports: any;
}

declare module 'typings-for-css-modules-loader/lib/persist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typings-for-css-modules-loader/lib/cssModuleHelper.js' {
  declare module.exports: $Exports<'typings-for-css-modules-loader/lib/cssModuleHelper'>;
}
declare module 'typings-for-css-modules-loader/lib/cssModuleToInterface.js' {
  declare module.exports: $Exports<'typings-for-css-modules-loader/lib/cssModuleToInterface'>;
}
declare module 'typings-for-css-modules-loader/lib/index.js' {
  declare module.exports: $Exports<'typings-for-css-modules-loader/lib/index'>;
}
declare module 'typings-for-css-modules-loader/lib/logger.js' {
  declare module.exports: $Exports<'typings-for-css-modules-loader/lib/logger'>;
}
declare module 'typings-for-css-modules-loader/lib/persist.js' {
  declare module.exports: $Exports<'typings-for-css-modules-loader/lib/persist'>;
}
