// flow-typed signature: c0a71ec4e8ec577bea332c3499be7afd
// flow-typed version: <<STUB>>/webpack-log_v^2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-log/src/index' {
  declare module.exports: any;
}

declare module 'webpack-log/src/loglevel/index' {
  declare module.exports: any;
}

declare module 'webpack-log/src/loglevel/LogLevel' {
  declare module.exports: any;
}

declare module 'webpack-log/src/loglevel/MethodFactory' {
  declare module.exports: any;
}

declare module 'webpack-log/src/loglevel/PrefixFactory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-log/src/index.js' {
  declare module.exports: $Exports<'webpack-log/src/index'>;
}
declare module 'webpack-log/src/loglevel/index.js' {
  declare module.exports: $Exports<'webpack-log/src/loglevel/index'>;
}
declare module 'webpack-log/src/loglevel/LogLevel.js' {
  declare module.exports: $Exports<'webpack-log/src/loglevel/LogLevel'>;
}
declare module 'webpack-log/src/loglevel/MethodFactory.js' {
  declare module.exports: $Exports<'webpack-log/src/loglevel/MethodFactory'>;
}
declare module 'webpack-log/src/loglevel/PrefixFactory.js' {
  declare module.exports: $Exports<'webpack-log/src/loglevel/PrefixFactory'>;
}
